syntax = "proto3";

package proto_aegis_grpc.v1;

import "google/protobuf/empty.proto";
import "proto_aegis_grpc/v1/control_msgs.proto";
import "proto_aegis_grpc/v1/geometry_msgs.proto";
import "proto_aegis_grpc/v1/sensor_msgs.proto";

service RobotReadService {
  rpc GetTCPPose(google.protobuf.Empty) returns (Pose);
  rpc GetWrench(google.protobuf.Empty) returns (Wrench);
  rpc GetJointStates(google.protobuf.Empty) returns (JointState);
  rpc GetCameraSceneImage(google.protobuf.Empty) returns (Image);
  rpc GetCameraRightImage(google.protobuf.Empty) returns (Image);
  rpc GetCameraLeftImage(google.protobuf.Empty) returns (Image);
  rpc GetAll(google.protobuf.Empty) returns (RobotState);
  rpc GetAllVis(google.protobuf.Empty) returns (RobotStateVis);
}

message RobotState {
  Pose pose = 1;
  Wrench wrench = 2;
  JointState joint_state = 3;
  Image image = 4;
}

message RobotStateVis {
  Pose pose = 1;
  Wrench wrench = 2;
  JointState joint_state = 3;
  Image image_scene = 4;
  Image image_right = 5;
  Image image_left = 6;
}

service RobotControlService {
  rpc ServoEnable(google.protobuf.Empty) returns (TriggerResponse);
  rpc ServoDisable(google.protobuf.Empty) returns (TriggerResponse);
  rpc ServoJoint(JointJog) returns (google.protobuf.Empty);
  rpc ServoTCP(Twist) returns (google.protobuf.Empty);
  rpc GotoPose(Pose) returns (TriggerResponse);
  rpc GotoJoints(JointState) returns (TriggerResponse);
  rpc GripperSetPosition(GripperSetPositionRequest) returns (TriggerResponse);
  rpc GripperClose(google.protobuf.Empty) returns (TriggerResponse);
  rpc GripperOpen(google.protobuf.Empty) returns (TriggerResponse);
}

// https://github.com/ros2/common_interfaces/blob/humble/std_srvs/srv/Trigger.srv
message TriggerResponse {
  bool success = 1;
  string msg = 2;
}

// https://github.com/ros-controls/control_msgs/blob/humble/control_msgs/action/GripperCommand.action
message GripperSetPositionRequest {
  double position = 1; // The goal gripper gap size (in meters)
  double effort = 2; // The goal effort exerted (in Newtons)
}
