syntax = "proto3";

package proto_aegis_grpc.v1;

// https://github.com/ros2/common_interfaces/blob/humble/sensor_msgs/msg/JointState.msg
message JointState {
  // This is a message that holds data to describe the state of a set of torque controlled joints.
  //
  // The state of each joint (revolute or prismatic) is defined by:
  //  * the position of the joint (rad or m),
  //  * the velocity of the joint (rad/s or m/s) and
  //  * the effort that is applied in the joint (Nm or N).
  //
  // Each joint is uniquely identified by its name
  // The header specifies the time at which the joint states were recorded. All the joint states
  // in one message have to be recorded at the same time.

  repeated string name = 1;
  repeated double position = 2;
  repeated double velocity = 3;
  repeated double effort = 4;
}

// https://github.com/ros2/common_interfaces/blob/rolling/sensor_msgs/msg/Image.msg
message Image {
  uint32 height = 1;
  uint32 width = 2;
  enum Encoding {
    UNKNOWN = 0;
    BGR8 = 1;
    BAYER_RGGB8 = 2;
  }
  Encoding encoding = 3;
  uint32 step = 4;
  bytes data = 5;
}
