/oak_d_pro_scene:
  ros__parameters:
    camera:
      i_ip: 169.254.1.100
      i_mx_id: 184430108157970F00
      i_nn_type: spatial
      i_pipeline_type: RGBD
    nn:
      i_disable_resize: true
      i_enable_passthrough: true
    rgb:
      i_enable_preview: true
      i_keep_preview_aspect_ratio: true
      i_preview_size: 416
    stereo:
      i_subpixel: true
  spatial_bb_node:
    ros__parameters:
      desqueeze: true
