# Camera parameters - default: pylon_ros_camera/pylon_ros2_camera_wrapper/config/default.yaml

/**:
  ros__parameters:

    #  The tf frame under which the images were published
    camera_frame: pylon_camera

    #  The DeviceUserID of the camera. If empty, the first camera found in the
    #  device list will be used
    device_user_id: ""

    #  The CameraInfo URL (Uniform Resource Locator) where the optional intrinsic
    #  camera calibration parameters are stored. This URL string will be parsed
    #  from the ROS-CameraInfoManager:
    camera_info_url: ""

    #  The encoding of the pixels -- channel meaning, ordering, size
    #  taken from the list of strings in include/sensor_msgs/image_encodings.h
    #  The supported encodings are 'mono8', 'bgr8', 'rgb8', 'bayer_bggr8',
    #  'bayer_gbrg8' and 'bayer_rggb8'
    #  Default values are 'mono8' and 'rgb8'
    image_encoding: 'rgb8'

    #  Binning factor to get downsampled images. It refers here to any camera
    #  setting which combines rectangular neighborhoods of pixels into larger
    #  "super-pixels." It reduces the resolution of the output image to
    #  (width / binning_x) x (height / binning_y).
    #  The default values binning_x = binning_y = 0 are considered the same
    #  as binning_x = binning_y = 1 (no subsampling).
    # binning_x: 1
    # binning_y: 1

    #  The desired publisher frame rate if listening to the topics.
    #  This parameter can only be set once at startup
    #  Calling the GrabImages-Action can result in a higher framerate
    frame_rate: 25.0
