/oak_d_pro:
  ros__parameters:
    camera:
      i_ip: 169.254.1.100
      i_mx_id: 184430108157970F00
      i_nn_type: spatial
      i_pipeline_type: RGBD
    rgb:
      i_enable_preview: true
      i_keep_preview_aspect_ratio: false
    nn:
      i_enable_passthrough: true
      i_disable_resize: true
    stereo:
      i_subpixel: true
  spatial_bb_node:
    ros__parameters:
      desqueeze: true
/oak_d_sr_left:
  ros__parameters:
    camera:
      i_ip: 169.254.1.12
      i_mx_id: 14442C10B1C1F1CF00
      i_pipeline_type: StereoToF
/oak_d_sr_right:
  ros__parameters:
    camera:
      i_ip: 169.254.1.11
      i_mx_id: 14442C10A19F37D200
      i_pipeline_type: StereoToF
