@startuml
package aegis_description {
    class aegis_urdf << (U,#bcffc8) urdf.xacro >> {
        arg mock_hardware="false"
    }
    class aegis << (X,cyan) xacro >> {}
    class cylinders_inertial << (X,cyan) xacro >> {}

    package modules {
        class cell << (X,cyan) xacro >> {}
        class luxonis_oakd_pro_scene << (X,cyan) xacro >> {}
        class ur_definition << (X,cyan) xacro >> {}
        class adapter_to_sensor << (X,cyan) xacro >> {}
        class ft_schunk_axia80 << (X,cyan) xacro >> {}
        class adapter_from_sensor << (X,cyan) xacro >> {}
    }

    package config {
        class initial_positions << (Y,#ffffc9) YAML >> {}
        package ur5e {
            class joint_limits << (Y,#ffffc9) YAML >> {}
            class physical_parameters << (Y,#ffffc9) YAML >> {}
            class visual_parameters << (Y,#ffffc9) YAML >> {}
            class calibration << (Y,#ffffc9) YAML >> {}
        }
    }
}

package aegis_moveit_config {
    class aegis << (S,#c298e9) SRDF >> {}
}

package robotiq_hande_gripper {
    class robotiq_hande_gripper << (X,cyan) xacro >> {}
}

package net_ft_description {
    class net_ft_sensor << (X,cyan) xacro >> {}
}

package ur_description {
    class ur_macro << (X,cyan) xacro >> {}
}

package ur_robot_driver {
    class ros_control << (U,#ffffc9) urscript >> {}
    class rtde_output_recipe << (T,#ffffc9) TXT >> {}
    class rtde_input_recipe << (T,#ffffc9) TXT >> {}
}


aegis_description.aegis_urdf *-right- aegis_description.aegis
aegis_description.aegis *-- aegis_description.modules
aegis_description.aegis *-- robotiq_hande_gripper.robotiq_hande_gripper

aegis_description.modules.adapter_from_sensor *-- aegis_description.cylinders_inertial
aegis_description.modules.adapter_to_sensor *-- aegis_description.cylinders_inertial
aegis_description.modules.ft_schunk_axia80 *-down- net_ft_description.net_ft_sensor
aegis_description.modules.ur_definition *-down- ur_description.ur_macro
aegis_description.modules.ur_definition *-right- ur_robot_driver
aegis_description.modules.ur_definition *-up- aegis_description.config

hide members
show << urdf.xacro >> fields
@enduml
