# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
#
# Based on the Universal Robots ROS2 Driver UR5e example
# Sources:
#  - Universal Robots e-Series, User Manual, UR5e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69091/99404_UR5e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

#TODO integrate the generated file with UR5e example
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# joint_limits:
#   elbow_joint:
#     has_velocity_limits: true
#     max_velocity: 3.1415926535897931
#     has_acceleration_limits: false
#     max_acceleration: 0
#   hande_left_finger_joint:
#     has_velocity_limits: true
#     max_velocity: 0.14999999999999999
#     has_acceleration_limits: false
#     max_acceleration: 0
#   hande_right_finger_joint:
#     has_velocity_limits: true
#     max_velocity: 0.14999999999999999
#     has_acceleration_limits: false
#     max_acceleration: 0
#   shoulder_lift_joint:
#     has_velocity_limits: true
#     max_velocity: 3.1415926535897931
#     has_acceleration_limits: false
#     max_acceleration: 0
#   shoulder_pan_joint:
#     has_velocity_limits: true
#     max_velocity: 3.1415926535897931
#     has_acceleration_limits: false
#     max_acceleration: 0
#   wrist_1_joint:
#     has_velocity_limits: true
#     max_velocity: 3.1415926535897931
#     has_acceleration_limits: false
#     max_acceleration: 0
#   wrist_2_joint:
#     has_velocity_limits: true
#     max_velocity: 3.1415926535897931
#     has_acceleration_limits: false
#     max_acceleration: 0
#   wrist_3_joint:
#     has_velocity_limits: true
#     max_velocity: 3.1415926535897931
#     has_acceleration_limits: false
#     max_acceleration: 0


joint_limits:
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: "360.0" #deg
    max_velocity: "180.0" #deg
    min_position: "-360.0" #deg
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: "360.0" #deg
    max_velocity: "180.0" #deg
    min_position: "-360.0" #deg
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    # we artificially limit this joint to half its actual joint position limit
    # to avoid (MoveIt/OMPL) planning problems, as due to the physical
    # construction of the robot, it's impossible to rotate the 'elbow_joint'
    # over more than approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    max_position: "180.0" #deg
    max_velocity: "180.0" #deg
    min_position: "-180.0" #deg
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: "360.0" #deg
    max_velocity: "180.0" #deg
    min_position: "-360.0" #deg
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: "360.0" #deg
    max_velocity: "180.0" #deg
    min_position: "-360.0" #deg
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: "360.0" #deg
    max_velocity: "180.0" #deg
    min_position: "-360.0" #deg
