/**:
  controller_manager:
    ros__parameters:
      net_ft_sensor_broadcaster:
        type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

      net_ft_diagnostic_broadcaster:
        type: net_ft_diagnostic_broadcaster/NetFTDiagnosticBroadcaster

  net_ft_sensor_broadcaster:
    ros__parameters:
      sensor_name: axia_fts_sensor
      frame_id: fts_link
