[project]
name = "aegis_grpc_client"
version = "0.1.0"
description = "A gRPC client to read and control the Aegis robot."
authors = [
    { name = "AGH Center of Excellence in Artificial Intelligence", email = "ceai@agh.edu.pl" }
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "grpcio<1.51",
    "grpcio-tools<1.51",
    "numpy>=1.26.4",
    "proto-aegis-grpc",
    "protobuf<3.21",
]

[project.optional-dependencies]
test = [
    "pytest>=8.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
