@startuml
package aegis_bringup {
    class bringup << (L,#FF7700) LaunchFile >> {
        Arg mock_hardware="false"
        Arg launch_rviz="true"
        Param namespace=""
        Param tf_prefix=""
    }
}

package aegis_control {
    class start_drivers << (L,#FF7700) LaunchFile >> {
        Param tf_prefix
        Param mock_hardware
        Node ros2_control::controller_manager()
    }
    class ur_driver << (L,#FF7700) LaunchFile >> {
        Param tf_prefix
        Param mock_hardware
        Node ur_driver::controller_stopper_node()
        Node ur_driver::ur_dashboard_client()
        Node ur_driver::ur_tool_communication()
        Node ur_driver::urscript_interface()
        Node ros2_control::controllers_spawner()
    }
    class ft_sensor_driver << (L,#FF7700) LaunchFile >> {
        Node ros2_control::controllers_spawner()
    }
    class depthai_cameras_driver << (L,#FF7700) LaunchFile >> {
        Node depthai_ros_driver::oak_d_pro_scene()
        Node image_proc::oak_d_pro_scene_rectify_color_node()
        Node depthai_filters::oak_d_pro_scene_spatial_bb_node()
        Node depth_image_proc::oak_d_pro_scene_point_cloud_xyzrgb_node()
    }

    package config {
        package controllers {
            class net_ft_broadcaster << (Y,#ffffc9) YAML >> {}
            class update_rate << (Y,#ffffc9) YAML >> {}
            class ur_drivers << (Y,#ffffc9) YAML >> {}
        }
        package cameras {
            class cameras << (Y,#ffffc9) YAML >> {}
        }
    }
}

package aegis_description {
    class aegis_preview << (L,#FF7700) LaunchFile >> {
        Launch urdf_launch/display.launch()
        Node static_transform_publisher()
    }

    class robot_description << (L,#FF7700) LaunchFile >> {
        Param tf_prefix
        Param mock_hardware
        Node robot_state_publisher()
    }

    package config {
        package ur5e {
            class calibration << (Y,#ffffc9) YAML >> {}
            class joint_limits << (Y,#ffffc9) YAML >> {}
        }
    }

    package urdf {
        class aegis_urdf << (U,#bcffc8) urdf.xacro >> {}
    }

    package rviz {
        class preview << (R,#ffffff) rviz >> {}
    }
}

package aegis_moveit_config {
    class move_group << (L,#FF7700) LaunchFile >> {
        Param mock_hardware
        Param launch_rviz
        Node move_group_node()
        Node rviz_node()
        Node tf_robot_base_node()
        Node tf_odom_node()
        Node scene_objects_manager_node()
    }
    package config {
        class aegis << (S,#c298e9) SRDF >> {}
        package move_group {
            class ompl_planning << (Y,#ffffc9) YAML >> {}
            class kinematics << (Y,#ffffc9) YAML >> {}
        }
        class moveit << (R,#ffffff) rviz >> {}
        class controlers_description << (Y,#ffffc9) YAML >> {}
    }
}


aegis_bringup.bringup *-left- aegis_control.start_drivers
aegis_bringup.bringup *-- aegis_moveit_config.move_group
aegis_bringup.bringup *-- aegis_description.robot_description
aegis_description.robot_description *-- aegis_description.urdf.aegis_urdf

aegis_control.start_drivers *-- aegis_control.ur_driver
aegis_control.start_drivers *-- aegis_control.ft_sensor_driver
aegis_control.start_drivers *-- aegis_control.depthai_cameras_driver
aegis_control.start_drivers *-- aegis_control.config.controllers
aegis_control.depthai_cameras_driver *-- aegis_control.config.cameras

aegis_moveit_config.move_group *-- aegis_moveit_config.config
aegis_moveit_config.move_group *-- aegis_description.config.ur5e

aegis_description.aegis_preview *-- aegis_description.rviz.preview

skinparam classAttributeIconSize 0
hide << YAML >> members
hide << urdf.xacro >> members
hide << SRDF >> members
hide << rviz >> members
@enduml
