<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find aegis_description)/urdf/cylinders_inertial.xacro" />

  <xacro:macro name="adapter_to_sensor" params="prefix parent">
    <xacro:property name="mass" value="0.242" />
    <xacro:property name="radius1" value="0.03025" />
    <xacro:property name="height1" value="0.0116" />
    <xacro:property name="radius2" value="0.04255" />
    <xacro:property name="height2" value="0.0094" />

    <joint name="${prefix}adapter_to_sensor_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${parent}" />
      <child link="${prefix}adapter_to_sensor" />
    </joint>

    <link name="${prefix}adapter_to_sensor">
      <visual>
        <origin xyz="0 0 ${0.5 * height1}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${radius1}" length="${height1}" />
        </geometry>
        <material name="black">
          <color rgba="0.04 0.04 0.04 1" />
        </material>
      </visual>
      <visual>
        <origin xyz="0 0 ${height1 + 0.5 * height2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${radius2}" length="${height2}" />
        </geometry>
        <material name="black">
          <color rgba="0.04 0.04 0.04 1" />
        </material>
      </visual>
      <xacro:cylinders_inertial r1="${radius1}" l1="${height1}" r2="${radius2}" l2="${height2}"
        m="${mass}" />
      <collision>
        <origin xyz="0 0 ${0.5 * (height1 + height2)}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${radius2}" length="${height1 + height2}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}adapter_to_sensor_end_joint" type="fixed">
      <origin xyz="0 0 ${height1 + height2}" rpy="0 0 0" />
      <parent link="${prefix}adapter_to_sensor" />
      <child link="${prefix}adapter_to_sensor_end" />
    </joint>

    <link name="${prefix}adapter_to_sensor_end" />

  </xacro:macro>

</robot>
