@startuml Launch Files

package aegis_bringup {
    class bringup << (L,#FF7700) LaunchFile >> {
        Arg namespace=""
        Arg tf_prefix=""
        Arg mock_hardware="false"
        Arg launch_rviz="true"
    }
}

package aegis_control {
    class start_drivers << (L,#FF7700) LaunchFile >> {
        Arg tf_prefix
        Arg mock_hardware
    }
    class ur_driver << (L,#FF7700) LaunchFile >> {
        Arg tf_prefix
        Arg mock_hardware
        Node control_node()
        Node ur_control_node()
        Node dashboard_client_node()
        Node tool_communication_node()
        Node controller_stopper_node()
        Node urscript_interface()
        Node controller_spawners()
    }

}

package aegis_description {
    class aegis_display << (L,#FF7700) LaunchFile >> {
        Launch urdf_launch/display.launch()
        Node static_transform_publisher()
    }

    class robot_description << (L,#FF7700) LaunchFile >> {
        Arg tf_prefix
        Arg mock_hardware
        Node robot_state_publisher()
    }

    package config {
        class controllers << (Y,#ffffc9) YAML >> {}
        package ur5e {
            class calibration << (Y,#ffffc9) YAML >> {}
            class joint_limits << (Y,#ffffc9) YAML >> {}
            class update_rate << (Y,#ffffc9) YAML >> {}
        }
    }

    package urdf {
        class aegis_urdf << (U,#bcffc8) urdf.xacro >> {}
    }
}

package aegis_moveit_config {
    class move_group << (L,#FF7700) LaunchFile >> {
        Arg mock_hardware
        Arg launch_rviz
        Node move_group_node()
        Node rviz_node()
        Node tf_robot_base_node()
        Node tf_odom_node()
        Node scene_objects_manager_node()
    }
    package config {
        class aegis << (S,#c298e9) SRDF >> {}
        package move_group {
            class ompl_planning << (Y,#ffffc9) YAML >> {}
            class kinematics << (Y,#ffffc9) YAML >> {}
        }
        class moveit << (R,#ffffff) rviz >> {}
        class controlers_description << (Y,#ffffc9) YAML >> {}
    }
}


aegis_bringup.bringup *-left- aegis_control.start_drivers
aegis_bringup.bringup *-- aegis_moveit_config.move_group
aegis_bringup.bringup *-- aegis_description.robot_description
aegis_description.robot_description *-- aegis_description.urdf.aegis_urdf

aegis_control.start_drivers *-- aegis_control.ur_driver
aegis_control.ur_driver *-- aegis_description.config.ur5e.update_rate
aegis_control.ur_driver *-- aegis_description.config.controllers

aegis_moveit_config.move_group *-- aegis_moveit_config.config
aegis_moveit_config.move_group *-- aegis_description.config.ur5e.joint_limits
aegis_moveit_config.move_group *-- aegis_description.config.ur5e.calibration

skinparam classAttributeIconSize 0
hide << YAML >> members
hide << urdf.xacro >> members
hide << SRDF >> members
hide << rviz >> members
@enduml
