# Configuration for the MoveIt2 move groups
controller_names:
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller
  # TODO(issue#3) create & integrate the gripper controller
  # - gripper_controller

scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    #TODO somehow apply the "tf_prefix" launch arg to this configuration file
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

# TODO(issue#3) create & integrate the gripper controller
# gripper_controller:
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: false
#   joints:
#     - hande_left_finger_joint
