UniqueSceneObjectExample:
  pretty_name: "table"
  type: box
  frame_id: world
  size:
    x: 0.84
    y: 0.55
    z: 0.82
  scale: 1.0
  pose:
    position:
      x: 0.0
      y: 0.6
      z: 0.41
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
