syntax = "proto3";

package proto_grpc_aegis.v1;

import "proto_grpc_aegis/v1/geometry_msgs.proto";
import "proto_grpc_aegis/v1/sensor_msgs.proto";

service MoveitService {
  rpc GotoPose(GotoPoseRequest) returns (GotoPoseResponse);
  rpc GotoJoints(GotoJointsRequest) returns (GotoJointsResponse);
}

message GotoPoseRequest {
  Pose goal = 1;
}

message GotoPoseResponse {
  bool success = 1;
}

message GotoJointsRequest {
  JointState goal = 1;
}

message GotoJointsResponse {
  bool success = 1;
}
