syntax = "proto3";

package proto_grpc_aegis.v1;

import "google/protobuf/empty.proto";
import "proto_grpc_aegis/v1/control_msgs.proto";
import "proto_grpc_aegis/v1/geometry_msgs.proto";
import "proto_grpc_aegis/v1/sensor_msgs.proto";

service RobotReadService {
  rpc GetTCPPose(google.protobuf.Empty) returns (Pose);
  rpc GetWrench(google.protobuf.Empty) returns (Wrench);
  rpc GetJointState(google.protobuf.Empty) returns (JointState);
}

service RobotControlService {
  rpc ServoJoint(JointJog) returns (google.protobuf.Empty);
  rpc ServoTCP(Twist) returns (google.protobuf.Empty);
  rpc GotoPose(Pose) returns (TriggerResponse);
  rpc GotoJoints(JointState) returns (TriggerResponse);
}

service GripperService {
  rpc SetWidth(GripperSetWidthRequest) returns (GripperSetWidthResponse);
  rpc Close(google.protobuf.Empty) returns (TriggerResponse);
  rpc Open(google.protobuf.Empty) returns (TriggerResponse);
}

message TriggerResponse {
  bool success = 1;
  string msg = 2;
}

message GripperSetWidthRequest {
  double position = 1; // The goal gripper gap size (in meters)
  double effort = 2; // The goal effort exerted (in Newtons)
}

message GripperSetWidthResponse {
  double position = 1; // The current gripper gap size (in meters)
  double effort = 2; // The current effort exerted (in Newtons)
  bool stalled = 3; // True iff the gripper is exerting max effort and not moving
  bool reached_goal = 4; // True iff the gripper position has reached the commanded setpoint
}
